name = "wormhole-relay"
main = "src/index.ts"
compatibility_date = "2025-02-14"
account_id = "c766c312cd089545cd36afdede71bb89"

[durable_objects]
bindings = [
  { name = "TUNNEL", class_name = "Tunnel" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Tunnel"]

[[routes]]
pattern = "*.wormhole.bar/*"
zone_id = "9c072e7ba0809f3a6ec55b6fdaa53ad1"

[[d1_databases]]
binding = "DB"
database_name = "wormhole-db"
database_id = "bb72debb-382b-431d-ac81-9df6fd84b765"
migrations_dir = "migrations"
